apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: swaggercompareweb-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: swaggercompareweb
    spec:
      containers:
      - name: swaggercompareweb
        image: gcr.io/double11-222123/swaggercompareweb:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
