apiVersion: v1
kind: Service
metadata:
  name: swaggercompareweb
  labels:
    app: swaggercompareweb
spec:
  selector:
    app: swaggercompareweb
  ports:
  - port: 80
    protocol: TCP
    nodePort: 30061
  type: LoadBalancer
