apiVersion: v1
kind: Service
metadata:
  name: swaggercompareweb
  labels:
    app: swaggercompareweb
spec:
  selector:
    app: swaggercompareweb
  ports:
  - port: 8080
    protocol: TCP
  type: LoadBalancer
